project_name: stackstate-cli
release:
  gitlab:
    owner: stackvista
    name: "{{ .ProjectName }}"
  name_template: '{{.Tag}}'
  disable: true
brews:
- name: "{{ .ProjectName }}"
  tap:
    owner: stackvista
    name: homebrew-tap
  commit_author:
    name: stackstatebot
    email: sts-admin@stackstate.com
  folder: Formula
  install: |
    bin.install "sts"
  test: |
    system "#{bin}/sts", "version"
  description: StackState CLI
  homepage: https://docs.stackstate.com
  url_template: https://stseuw1-tooling-main-homebrew.s3-eu-west-1.amazonaws.com/{{ .ProjectName }}/{{.Tag}}/{{ .ArtifactName }}
  goarm: "6"
before:
  hooks:
    - go mod download
    - go get github.com/markbates/pkger/cmd/pkger
    - go generate ./...
builds:
- id: stackstate-cli
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  goarm:
  - "6"
  targets:
  - darwin_amd64
  - linux_amd64
  - windows_amd64
  main: .
  ldflags:
  - -s -w -X gitlab.com/stackvista/stackstate-cli2/cmd.Version={{.Version}}
    -X gitlab.com/stackvista/stackstate-cli2/cmd.Commit={{.Commit}}
    -X gitlab.com/stackvista/stackstate-cli2/cmd.Date={{.Date}}
    -X main.builtBy=goreleaser
  binary: sts
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
archives:
- id: stackstate-cli
  builds:
  - stackstate-cli
  name_template: '{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}'
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - none*
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
blobs:
  - provider: s3
    region: eu-west-1
    bucket: stseuw1-tooling-main-homebrew
    ids:
      - stackstate-cli