project_name: stackstate-cli
release:
  gitlab:
    owner: stackvista
    name: stackstate-cli2
  name_template: '{{.Tag}}'
  disable: true
before:
  hooks:
    - go mod download
builds:
- id: stackstate-cli-full
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  goarm:
  - "6"
  targets:
  - darwin_amd64
  - darwin_arm64
  - linux_amd64
  - linux_arm64
  - windows_amd64
  main: .
  ldflags:
  - -s -w -X gitlab.com/stackvista/stackstate-cli2/static_info.Version={{.Version}}
    -X gitlab.com/stackvista/stackstate-cli2/static_info.Commit={{.Commit}}
    -X gitlab.com/stackvista/stackstate-cli2/static_info.BuildDate={{.Date}}
    -X gitlab.com/stackvista/stackstate-cli2/static_info.CLIType=full
    -X static_info.builtBy=goreleaser
  binary: sts
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
- id: stackstate-cli-saas
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  goarm:
  - "6"
  targets:
  - darwin_amd64
  - darwin_arm64
  - linux_amd64
  - linux_arm64
  - windows_amd64
  main: .
  ldflags:
  - -s -w -X gitlab.com/stackvista/stackstate-cli2/static_info.Version={{.Version}}
    -X gitlab.com/stackvista/stackstate-cli2/static_info.Commit={{.Commit}}
    -X gitlab.com/stackvista/stackstate-cli2/static_info.BuildDate={{.Date}}
    -X gitlab.com/stackvista/stackstate-cli2/static_info.CLIType=saas
    -X main.builtBy=goreleaser
  binary: sts
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
archives:
- id: stackstate-cli-full
  builds:
  - stackstate-cli-full
  name_template: '{{ .ProjectName }}-full-{{ .Version }}.{{ .Os }}-{{ .Arch }}'
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - none*
  replacements:
    amd64: x86_64
- id: stackstate-cli-saas
  builds:
  - stackstate-cli-saas
  name_template: '{{ .ProjectName }}-saas-{{ .Version }}.{{ .Os }}-{{ .Arch }}'
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - none*
  replacements:
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
  algorithm: sha256
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
blobs:
  - provider: s3
    bucket: cli-dl.stackstate.com
    ids:
      - stackstate-cli-full
      - stackstate-cli-saas
brews:
- name: stackstate-cli
  ids:
    - stackstate-cli-full
  tap:
    owner: stackvista
    name: homebrew-tap
  commit_author:
    name: stackstatebot
    email: sts-admin@stackstate.com
  folder: Formula
  install: |
    bin.install "sts"
  test: |
    system "#{bin}/sts", "version"
  description: StackState CLI
  homepage: https://docs.stackstate.com
  url_template: https://dl.stackstate.com/{{ .ProjectName }}/{{.Tag}}/{{ .ArtifactName }}
  caveats: "Run `sts` to get going!"
dockers:
- image_templates:
  - "stackstate/stackstate-cli-full:{{ .Version }}-amd64"
  ids:
    - stackstate-cli-full
  use: buildx
  dockerfile: docker/Dockerfile.goreleaser
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "stackstate/stackstate-cli-full:{{ .Version }}-arm64v8"
  ids:
    - stackstate-cli-full
  use: buildx
  goarch: arm64
  dockerfile: docker/Dockerfile.goreleaser
  build_flag_templates:
  - "--platform=linux/arm64/v8"
- image_templates:
  - "stackstate/stackstate-cli-saas:{{ .Version }}-amd64"
  ids:
    - stackstate-cli-saas
  use: buildx
  dockerfile: docker/Dockerfile.goreleaser
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "stackstate/stackstate-cli-saas:{{ .Version }}-arm64v8"
  ids:
    - stackstate-cli-saas
  use: buildx
  goarch: arm64
  dockerfile: docker/Dockerfile.goreleaser
  build_flag_templates:
  - "--platform=linux/arm64/v8"
docker_manifests:
- name_template: stackstate/stackstate-cli:{{ .Version }}
  image_templates:
  - stackstate/stackstate-cli:{{ .Version }}-amd64
  - stackstate/stackstate-cli:{{ .Version }}-arm64v8