project_name: stackstate-cli
release:
  gitlab:
    owner: stackvista
    name: stackstate-cli2
  name_template: '{{.Tag}}'
before:
  hooks:
    - go mod download
builds:
- id: stackstate-cli
  goos:
  - darwin
  - linux
  - windows
  goarch:
  - amd64
  - arm64
  goarm:
  - "6"
  targets:
  - darwin_amd64
  - darwin_arm64
  - linux_amd64
  - linux_arm64
  - windows_amd64
  main: .
  ldflags:
  - -s -w -X gitlab.com/stackvista/stackstate-cli2/static_info.Version={{.Version}}
    -X gitlab.com/stackvista/stackstate-cli2/static_info.Commit={{.Commit}}
    -X gitlab.com/stackvista/stackstate-cli2/static_info.BuildDate={{.Date}}
    -X static_info.builtBy=goreleaser
  binary: sts
  env:
  - CGO_ENABLED=0
  - GO111MODULE=on
archives:
- id: stackstate-cli
  builds:
  - stackstate-cli
  name_template: '{{ .ProjectName }}-{{ .Version }}.{{ .Os }}-{{ .Arch }}'
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  files:
  - release-notes.md
  - release-notes.json
  replacements:
    amd64: x86_64
blobs:
  - provider: s3
    bucket: cli-dl.stackstate.com
    ids:
      - stackstate-cli
brews:
- name: stackstate-cli
  ids:
    - stackstate-cli
  tap:
    owner: stackvista
    name: homebrew-tap
  commit_author:
    name: stackstatebot
    email: sts-admin@stackstate.com
  folder: Formula
  install: |
    bin.install "sts"
  test: |
    system "#{bin}/sts", "version"
  description: StackState CLI
  homepage: https://docs.stackstate.com
  url_template: https://dl.stackstate.com/{{ .ProjectName }}/{{.Tag}}/{{ .ArtifactName }}
  caveats: "Run `sts` to get going!"
dockers:
- image_templates:
  - "stackstate/stackstate-cli2:{{ .Version }}-x86_64"
  ids:
    - stackstate-cli
  use: buildx
  dockerfile: docker/Dockerfile.goreleaser
  build_flag_templates:
  - "--platform=linux/amd64"
- image_templates:
  - "stackstate/stackstate-cli2:{{ .Version }}-arm64v8"
  ids:
    - stackstate-cli
  use: buildx
  goarch: arm64
  dockerfile: docker/Dockerfile.goreleaser
  build_flag_templates:
  - "--platform=linux/arm64/v8"
docker_manifests:
- name_template: stackstate/stackstate-cli2:{{ .Version }}
  image_templates:
  - stackstate/stackstate-cli2:{{ .Version }}-x86_64
  - stackstate/stackstate-cli2:{{ .Version }}-arm64v8
- name_template: stackstate/stackstate-cli2:latest
  image_templates:
  - stackstate/stackstate-cli2:{{ .Version }}-x86_64
  - stackstate/stackstate-cli2:{{ .Version }}-arm64v8
