openapi: 3.0.3
info:
  contact:
    email: info@stackstate.com
    name: StackState
    url: https://stackstate.com
  description: StackState's API specification
  license:
    name: Proprietary
    url: https://stackstate.com
  title: StackState API
  version: 0.0.1
externalDocs:
  description: Documentation
  url: https://docs.stackstate.com/
servers:
- url: /
security:
- ApiToken: []
paths:
  /import:
    post:
      description: Import
      operationId: importSettings
      requestBody:
        content:
          plain/text:
            schema:
              type: string
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  type: object
                type: array
          description: Result of executing the script.
      summary: 'Import '
components:
  schemas: {}
  securitySchemes:
    ApiToken:
      in: header
      name: X-API-Token
      type: apiKey
