gitHost: gitlab.com
gitUserId: stackvista
gitRepoId: stackstate-cli2
packageName: stackstate_old_client
useOneOfDiscriminatorLookup: true # needed for polymorphic types (using _type discriminator)
generateInterfaces: true # needed for testing