name: 'Base Go CI Image'
description: 'Run a command in a Go CI container'
inputs:
  image:
    description: 'CI Image'
    required: true
  options:
    description: 'Extra options for the container'
    required: false
  run:
    description: 'Run command in the container'
    required: false
runs:
  using: 'composite'
  steps:
    - uses: ./.github/actions/quay
      with:
        image: ${{ inputs.image }}
        options: ${{ inputs.options }} # NOTE: Assumes the repo is checked out beforehand.
        # NOTE: The git safe.directory is needed for goreleaser to work correctly.
        run: |-
          git config --global --add safe.directory /workspace
          cd /workspace
          ${{ inputs.run }}
