name: CI
on:
  pull_request:
    branches: [ main ]

  # Allows to run this via the Actions tab
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v17
        with:
          nix_conf:
            experimental-features = nix-command flakes

      - name: Compute Image Checksum
        run: echo "NIX_CHECKSUM=$(cat flake.* | md5sum | awk '{print $1}')" >> $GITHUB_ENV

      - name: Run Nix
        run: |
          nix profile install nixpkgs#docker
          nix build .#ci-image

      - name: Publish base image
        env:
          DOCKER_TLS_CERTDIR: ""
          CI_BASE_IMAGE_PUSH: quay.io/stackstate/sts-ci-images:stackstate-cli2-${{ env.NIX_CHECKSUM }}
        run: |
          docker load < result
          docker tag stackstate-cli2-ci:latest $CI_BASE_IMAGE_PUSH
          docker push $CI_BASE_IMAGE_PUSH

      - name: Go base
        run: echo "TODO"

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: echo "${{env.NIX_CHECKSUM}}"

      - name: Lint
        run: ./scripts/lint.sh

      - name: Check StackState API up to date
        run: ./scripts/check_stackstate_api_up-to-date.sh

      - name: License scanning
        run: echo "TODO"

      - name: Dependency scanning
        run: echo "TODO"

      - name: Go releaser check
        run: goreleaser check

      - name: Compile test
        run: go test ./... -v

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate release notes
        run: echo "TODO"

      - name: Publish
        run: echo "TODO"

