name: CI
on:
  pull_request:
    branches: [ main ]

  # Allows to run this via the Actions tab
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Nix Checksum
        run: echo "NIX_CHECKSUM=$(cat flake.* | md5sum | awk '{print $1}')" >> $GITHUB_ENV

      - name: Publish base image
        uses: addnab/docker-run-action@v3
        with:
          image: "nixos/nix:2.8.0"
          username: ${{ secrets.QUAY_USER }}
          password: ${{ secrets.QUAY_PASSWORD }}
          registry: quay.io
          options: >-
            -e NIX_CONFIG="experimental-features = nix-command flakes"
            -e DOCKER_DRIVER="overlay2"
            -e DOCKER_HOST="tcp://docker:2375"
            -e DOCKER_TLS_CERTDIR=""
            -e CI_BASE_IMAGE_PUSH="quay.io/stackstate/sts-ci-images:stackstate-cli2-${{ env.NIX_CHECKSUM }}"
          run: |
            cd /github/workspace
            nix profile install nixpkgs#docker
            nix build .#ci-image
            echo "$CI_BASE_IMAGE_PUSH"
            #docker load < result
            #docker tag stackstate-cli2-ci:latest $CI_BASE_IMAGE_PUSH
            #docker push $CI_BASE_IMAGE_PUSH

      - name: Go base
        run: echo "TODO"

  check:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Test
        run: echo "${{env.NIX_CHECKSUM}}"

      - name: Lint
        run: ./scripts/lint.sh

      - name: Check StackState API up to date
        run: ./scripts/check_stackstate_api_up-to-date.sh

      - name: License scanning
        run: echo "TODO"

      - name: Dependency scanning
        run: echo "TODO"

      - name: Go releaser check
        run: goreleaser check

      - name: Compile test
        run: go test ./... -v

  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate release notes
        run: echo "TODO"

      - name: Publish
        run: echo "TODO"

