name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows to run this via the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Nix Checksum
        run: echo "TODO"

      - name: Publish base image
        run: echo "TODO"

      - name: Go base
        run: echo "TODO"

      - name: Lint
        run: ./scripts/lint.sh

      - name: Check StackState API up to date
        run: ./scripts/check_stackstate_api_up-to-date.sh

      - name: License scanning
        run: echo "TODO"

      - name: Dependency scanning
        run: echo "TODO"

      - name: Go releaser check
        run: goreleaser check

      - name: Compile test
        run: go test ./... -v

      - name: Generate release notes
        run: echo "TODO"

      - name: Publish
        run: echo "TODO"

