name: CI
on:
  pull_request:
    branches: [ main ]

  # Allows to run this via the Actions tab
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Compute Image Checksum
        run: echo "NIX_CHECKSUM=$(cat flake.* | md5sum | awk '{print $1}')" >> $GITHUB_ENV

      - name: Cache Image
        id: cache-image
        uses: actions/cache@v3
        with:
          path: result
          key: cli-ci-image-${{ env.NIX_CHECKSUM }}

      - name: Install Nix
        if: steps.cache-image.outputs.cache-hit != 'true'
        uses: nixbuild/nix-quick-install-action@v17
        with:
          nix_conf:
            experimental-features = nix-command flakes

      - name: Run Nix
        if: steps.cache-image.outputs.cache-hit != 'true'
        run: |
          nix profile install nixpkgs#docker
          nix build .#ci-image

      - name: Publish base image
        if: steps.cache-image.outputs.cache-hit != 'true'
        env:
          DOCKER_TLS_CERTDIR: ""
          CI_BASE_IMAGE_PUSH: quay.io/stackstate/sts-ci-images:stackstate-cli2-${{ env.NIX_CHECKSUM }}
        run: |
          echo "${{ secrets.QUAY_PASSWORD }}" | docker login --username=${{ secrets.QUAY_USER }} --password-stdin quay.io
          docker load < result
          docker tag stackstate-cli2-ci:latest $CI_BASE_IMAGE_PUSH
          docker push $CI_BASE_IMAGE_PUSH

    outputs:
      nixChecksum: ${{ env.NIX_CHECKSUM }}
      ciImageName: quay.io/stackstate/sts-ci-images:stackstate-cli2-${{ env.NIX_CHECKSUM }}

  check:
    needs: setup
    runs-on: ubuntu-latest
    env:
      QUAY_USER: ${{ secrets.QUAY_USER }}
      QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}

    steps:
      - uses: actions/checkout@v3

      - name: Lint
        uses: ./.github/actions/gobase
        with:
          image: ${{ needs.setup.outputs.ciImageName }}
          run: ./scripts/lint.sh

      # TODO Needs the open-api repo to be available.
      - name: Check StackState API up to date
        if: false
        uses: ./.github/actions/gobase
        with:
          image: ${{ needs.setup.outputs.ciImageName }}
          run: ./scripts/check_stackstate_api_up-to-date.sh

      - name: License scanning
        run: echo "TODO"

      - name: Dependency scanning
        run: echo "TODO"

      - name: Go releaser check
        uses: ./.github/actions/gobase
        with:
          image: ${{ needs.setup.outputs.ciImageName }}
          run: goreleaser check

      - name: Compile test
        uses: ./.github/actions/gobase
        with:
          image: ${{ needs.setup.outputs.ciImageName }}
          run: go test ./... -v

  deploy:
    needs: [setup, check]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Generate release notes
        run: echo "TODO"

      - name: Publish
        run: echo "TODO"

