openapi: 3.0.3
info:
  description: StackState's API specification
  version: 0.0.1
  title: StackState API
  license:
    name: Proprietary
    url: "https://stackstate.com"
  contact:
    name: StackState
    email: info@stackstate.com
    url: "https://stackstate.com"
externalDocs:
  description: Documentation
  url: "https://docs.stackstate.com/"
security:
  - ApiToken: []
paths:
  /import:
    $ref: "import.api.yaml#/paths/%2Fimport"

components:
  securitySchemes:
    ApiToken:
      type: apiKey
      in: header
      name: X-API-Token
